site_name: JPN-API

copyright: "This website is not produced, endorsed, supported, or affiliated with Nintendo, The Pokémon Company, Digimon, DRAGON BALL SUPER CARD GAME, Bandai Namco, or my employer."

extra:
  homepage: "home"
  social: 
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/ur69hxZ8rm"
    - icon: fontawesome/brands/github
      link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

theme:
  name: material

  icon:
    logo: material/alpha-j-circle

  features:
    - navigation.top
    - navigation.expand

  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: home.md
  - 'API Documentation': 
    - "Japanese Pokemon TCG":
      - "Version 2": 
        - "Objects": 'api_docs/pokemon/v2/v2_obj.md'
        - "API Queries": 'api_docs/pokemon/v2/v2_api.md'
      - "Version 1": 
        - "Objects": 'api_docs/pokemon/v1/v1_obj.md'
        - "API Queries": "api_docs/pokemon/v1/v1_api.md"
    - "Dragonball Super TCG": "api_docs/dbz.md"
    - "Digimon CCG": "api_docs/digimon.md"
  - About: 
    - "FAQs": "about/faq.md"
    - "About the API": "about/about.md"
    - "Contact": "about/contact.md"
    - "Contribute": "about/contribute.md"
    - "Donate": "https://ko-fi.com/jpnapi"